config/routes.rb
Rails.application.routes.draw do
  
  namespace :admin do
    resource  :free_shipping_settings
  end
  
end

app/models/calculator/free_shipping.rb
class Calculator::FreeShipping < Calculator
  preference :amount, :decimal, :default => 0

  def self.description
    "Free Shipping"
  end

  def self.register
    super                                
    ShippingMethod.register_calculator(self)
  end  
  
  def compute(object=nil)
    0
  end  
 
  def available?(object)
    object.eligible_for_free_shipping?
  end
end

app/controllers/admin/free_shipping_settings_controller.rb
class Admin::FreeShippingSettingsController < Admin::BaseController

  def update
    Spree::Config.set(params[:preferences])
    
    respond_to do |format|
      format.html {
        redirect_to admin_free_shipping_settings_path
      }
    end
  end

end

app/views/admin/free_shipping_settings/edit.html.erb
<%= render :partial => 'admin/shared/configuration_menu' %>

<h1>Free Shipping Settings</h1>

<% form_tag(admin_free_shipping_settings_path, :method => :put) do -%>

  <p>
    <label>Free shipping after this amount added to cart:</label><br />
    <%= text_field_tag('preferences[free_shipping_amount]', Spree::Config[:free_shipping_amount], :maxlength => 10)%>
    <br/>
  </p>
  
 

  <p class="form-buttons">
    <%= button t('update') %>
  </p>

<% end -%>

app/views/admin/free_shipping_settings/show.html.erb
<%= render :partial => 'admin/shared/configuration_menu' %>

<h1>Free Shipping Settings</h1>

<h4>Free shipping for all orders over: <%=  Spree::Config[:free_shipping_amount] %> </h4>

<%= link_to_with_icon 'edit', t("edit"), edit_admin_free_shipping_settings_path %>